receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    send_batch_size: 512
    timeout: 1s

exporters:
  kafka:
    brokers:
      - kafka:29092
    topic: netstream-metrics

  debug:
    verbosity: detailed

service:
  telemetry:
    logs:
      level: debug
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [kafka, debug]
