// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PacketMetric {
    #[prost(uint32, tag = "1")]
    pub protocol: u32,
    #[prost(uint64, tag = "2")]
    pub count: u64,
}
